#ifndef STATUS_H
#define STATUS_H

typedef enum {
    STATUS_OK = 200,
    STATUS_BAD_REQUEST = 400,
    STATUS_NOT_FOUND = 404,
    STATUS_CONFLICT = 409,
    STATUS_MEMORY_ALLOCATION_ERROR = 503,
    STATUS_UNDEFINED_TYPE = 504,
} STATUS;

#endif